# Generated by Django 5.2.1 on 2025-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_produto_data_adicionado_produto_promocao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_promocional",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
