# Generated by Django 5.2.1 on 2025-05-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_produto_preco_promocional"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="promocao",
            field=models.BooleanField(default=False),
        ),
    ]
