# Generated by Django 5.2.1 on 2025-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_categoria_promocao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="banner",
            field=models.BooleanField(default=False),
        ),
    ]
