# Generated by Django 5.2.1 on 2025-05-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_banners"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Banners",
            new_name="Banner",
        ),
    ]
